version: "3"
services:
	nginx:
		build: ./requirements/nginx
		dockerfile: Dockerfile
		container_name: nginx
		port:
			- "443:443"
		depends_on:
			- wordpress
		env_file: .env
		volumes:
			- wp_vol:/var/www/html
		networks:
			- inception
		restart: unless-stopped
	wordpress:
		build: ./requirements/wordpress
		dockerfile: Dockerfile
		container_name: wordpress
		depends_on:
			- mariadb
		env_file: .env
		volumes:
			-wp_vol:/var/www/html
		networks:
			-inception
		restart: unless-stopped
	mariadb:
		build: ./requirements/mariadb
		dockerfile: Dockerfile
		container_name: mariadb
		env_file: .env
		volumes:
			-db_vol:/var/lib/mysqld
		networks:
			-inception
		restart: unless-stopped

	networks:
		inception:

	volumes:
		wp_vol:
			driver: local
			driver_opts:
				type: none
				device: /home/lmasson/data/wp_vol
				o: bind
		db_vol:
			driver: local
			driver_opts:
				type: none
				device: /home/lmasson/data/db_vol
				o: bind
